from typing import Final

from imbue.changelings.errors import ChangelingConfigError
from imbue.changelings.primitives import ChangelingTemplateName
from imbue.imbue_common.pure import pure

_CODE_GUARDIAN_MESSAGE: Final[str] = """\
Read all documentation in the docs/ directory of this project. Read the style guide. Read all README.md files.
Then read all code at the root of the project (primitives.py, data_types.py, errors.py, etc.).
Then read all code in data_types, interfaces, and utils directories.
Then read the remaining code directories and files relevant to identifying inconsistencies.

Your task is to identify the most important inconsistencies in this codebase.

Focus on code-level issues:
- Things done in different ways in different places
- Inconsistent variable/function/class naming
- Architectural inconsistencies
- Patterns used in some places but not others

Do NOT worry about docstrings, comments, or documentation -- focus only on the code itself.
Do NOT worry about inconsistencies between the docs/specs and the code.
Do NOT report issues already covered by existing FIXMEs.
Do NOT report issues highlighted as non-issues in non_issues.md (if it exists).

After reviewing all the code, create a markdown report with the most important inconsistencies,
ordered from most important to least important. Save the report to a file named
`_tasks/inconsistencies/<date>.md` where `<date>` is generated by running:
  date +%Y-%m-%d-%T | tr : -

Use this format for the report:

```markdown
# Inconsistencies report (identified on <date>)

## 1. <Short description of inconsistency>

Description: <detailed description, including file names and line numbers>

Recommendation: <your recommendation for how to fix it>

Decision: Accept

## 2. <Short description of inconsistency>
...
```

After creating the report, commit it with a clear commit message like
"changeling/code-guardian: inconsistencies report <date>".

Then create a PR with the title "changeling/code-guardian: inconsistencies report <date>".
The PR body should summarize the top 3-5 issues found.
"""

_FIXME_FAIRY_MESSAGE: Final[str] = """\
Read all documentation per the instructions in CLAUDE.md.

Your task is to find and fix FIXMEs in this codebase.

Search the entire codebase for FIXME comments. For each FIXME you find:
1. Understand the context and what needs to be fixed
2. Implement the fix
3. Remove the FIXME comment
4. Commit the fix with a clear commit message

Fix one FIXME per commit. After fixing all FIXMEs (or as many as you can),
create a PR with the title "changeling/fixme-fairy: fix FIXMEs" summarizing
all the fixes you made.
"""

_TEST_TROLL_MESSAGE: Final[str] = """\
Read all documentation per the instructions in CLAUDE.md.

Your task is to improve the tests in this codebase. Focus on:
1. Speeding up slow tests
2. Removing redundant or pointless tests
3. Fixing flaky tests
4. Increasing test coverage for under-tested areas

Make each improvement in a separate commit. After making improvements,
create a PR with the title "changeling/test-troll: test improvements"
summarizing all changes.
"""

_COVERAGE_HUNTER_MESSAGE: Final[str] = """\
Read all documentation per the instructions in CLAUDE.md.

Your task is to increase test coverage in this codebase.

Run the test suite and examine coverage reports to find under-tested code.
Write new tests to cover untested paths. Focus on:
1. Important business logic that lacks coverage
2. Error handling paths
3. Edge cases

Do NOT sacrifice test speed for coverage. Each test should be fast.
Commit each new test file or test addition separately.
After adding tests, create a PR with the title "changeling/coverage-hunter: increase coverage"
summarizing the coverage improvements.
"""

_DOC_REGENT_MESSAGE: Final[str] = """\
Read all documentation per the instructions in CLAUDE.md.

Your task is to identify places where the documentation and code disagree.
Focus on user-facing docs (docs/ directory, README files).

Create a markdown report listing all doc/code disagreements, ordered by importance.
Save the report to `_tasks/doc-code-disagreements/<date>.md`.

After creating the report, commit it and create a PR with the title
"changeling/doc-regent: doc/code disagreements report <date>".
"""

_DOCSTRING_SCRIBE_MESSAGE: Final[str] = """\
Read all documentation per the instructions in CLAUDE.md.

Your task is to identify outdated docstrings in this codebase.
Look for docstrings that no longer match what the code actually does.

Create a markdown report listing all outdated docstrings, ordered by importance.
Save the report to `_tasks/outdated-docstrings/<date>.md`.

After creating the report, commit it and create a PR with the title
"changeling/docstring-scribe: outdated docstrings report <date>".
"""

_SECURITY_SOLDIER_MESSAGE: Final[str] = """\
Read all documentation per the instructions in CLAUDE.md.

Your task is to identify potential security issues in this codebase.
Focus on OWASP top 10 vulnerabilities and common security anti-patterns.

Create a markdown report listing all potential security issues, ordered by severity.
Save the report to `_tasks/security-issues/<date>.md`.

After creating the report, commit it and create a PR with the title
"changeling/security-soldier: security report <date>".
"""

_ISSUE_SERVANT_MESSAGE: Final[str] = """\
Read all documentation per the instructions in CLAUDE.md.

Your task is to look at open GitHub issues and attempt to fix them.
Use `gh issue list` to find open issues. Pick one that seems tractable,
implement a fix, and create a PR that references the issue.

Use the PR title format "changeling/issue-servant: fix #<issue_number>".
"""

_MODULE_WARDEN_MESSAGE: Final[str] = """\
Read all documentation per the instructions in CLAUDE.md.

Your task is to review and improve a specific sub-module of the codebase.
Pick the module that would benefit most from improvement.

Focus on:
1. Code quality and consistency
2. Test coverage
3. Documentation accuracy
4. Error handling

Make improvements in separate commits. Create a PR with the title
"changeling/module-warden: improve <module_name>".
"""


TEMPLATE_MESSAGE_BY_NAME: Final[dict[ChangelingTemplateName, str]] = {
    ChangelingTemplateName("code-guardian"): _CODE_GUARDIAN_MESSAGE,
    ChangelingTemplateName("fixme-fairy"): _FIXME_FAIRY_MESSAGE,
    ChangelingTemplateName("test-troll"): _TEST_TROLL_MESSAGE,
    ChangelingTemplateName("coverage-hunter"): _COVERAGE_HUNTER_MESSAGE,
    ChangelingTemplateName("doc-regent"): _DOC_REGENT_MESSAGE,
    ChangelingTemplateName("docstring-scribe"): _DOCSTRING_SCRIBE_MESSAGE,
    ChangelingTemplateName("security-soldier"): _SECURITY_SOLDIER_MESSAGE,
    ChangelingTemplateName("issue-servant"): _ISSUE_SERVANT_MESSAGE,
    ChangelingTemplateName("module-warden"): _MODULE_WARDEN_MESSAGE,
}

KNOWN_TEMPLATE_NAMES: Final[frozenset[ChangelingTemplateName]] = frozenset(TEMPLATE_MESSAGE_BY_NAME.keys())


@pure
def get_template_message(template_name: ChangelingTemplateName) -> str:
    """Get the default initial message for a changeling template."""
    if template_name not in TEMPLATE_MESSAGE_BY_NAME:
        raise ChangelingConfigError(
            f"Unknown template '{template_name}'. Known templates: {', '.join(sorted(KNOWN_TEMPLATE_NAMES))}"
        )
    return TEMPLATE_MESSAGE_BY_NAME[template_name]


@pure
def is_known_template(template_name: ChangelingTemplateName) -> bool:
    """Check if a template name is a known built-in template."""
    return template_name in KNOWN_TEMPLATE_NAMES
